print(3/0)
print(-3/0)
print(exp(-Inf))
print(0/Inf)
print(0^Inf)
print(0^0)
print(1^Inf)
print((0:3)^Inf)
print(0/0)
print(Inf-Inf)
print(Inf/Inf)
print(is.nan(0/0)) #similarly check is.na() where applicable
print(is.finite(10))
print(is.infinite(10))
print(is.infinite(Inf))
y <- c(4,NA,7)
print(is.na(y))
print(y[!is.na(y)])
y1 <- c(1,2,3,NA)
y2 <- c(5,6,NA,8)
y3 <- c(9,NA,11,12)
y4 <- c(NA,14,15,16)
full.frame <- data.frame(y1,y2,y3,y4)
print(full.frame)
reduced.frame <- full.frame[!is.na(full.frame$y1),]
print(reduced.frame)
x <- c(1:8,NA)
print(x)
print(mean(x)) #mean() does not work with NA
print(mean(x,na.rm=TRUE))
vmv <- c(1:6,NA,NA,9:12)
print(vmv)
print(seq(along=vmv)[is.na(vmv)])
print(which(is.na(vmv)))
vmv[is.na(vmv)] <- 0
print(vmv)
vmv <- c(1:6,NA,NA,9:12)
vmv <- ifelse(is.na(vmv),0,vmv)
print(vmv)
