print(T==F)
T <- 0
print(T == FALSE)
print(T != F)
x <- sqrt(2)
print(x * x == 2)
print(x * x - 2)
x <- 0.3 - 0.2
y <- 0.1
print(x == y)
print(identical(x,y))
print(all.equal(x,y))
a <- c("cat","dog","goldfish")
b <- factor(a)
print(all.equal(a,b))
print(class(b))
print(class(a))
print(mode(b))
print(mode(a))
print(attributes(b))
print(attributes(a))
n1 <- c(1,2,3)
n2 <- c(1,2,3,4)
print(all.equal(n1,n2))
n2 <- as.character(n2)
print(all.equal(n1,n2))
x <- c(NA, FALSE, TRUE)
names(x) <- as.character(x)
print(names(x))
print(outer(x, x, "&"))
print(outer(x, x, "|"))
x <- 0:6
print(x < 4)
print(all(x>0))
print(any(x<0))
print(sum(x<4))
print((x<4)*runif(7))
(treatment <- letters[1:5])
(t1<- factor(1+(treatment=="b")))
(x)
(t2 <- factor(1+(treatment=="b")+2*(treatment=="c")+2*(treatment=="d")))


